# Generated by Django 4.2.10 on 2024-03-06 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3)),
                ('sqft', models.IntegerField()),
                ('description', models.TextField()),
                ('lotsize', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Lot Size')),
                ('tax_assessment', models.IntegerField()),
                ('tax_year', models.IntegerField()),
                ('listed_by', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('house', 'House'), ('lot', 'Lot'), ('multifamily', 'Multi-family'), ('condo', 'Condominium'), ('townhomes', 'Townhomes')], default='house', max_length=50)),
                ('property_taxes', models.IntegerField()),
                ('original_url', models.URLField(max_length=255, null=True, verbose_name='Original URL')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
