# Generated by Django 4.2.10 on 2024-03-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('sqft', models.IntegerField()),
                ('description', models.TextField()),
                ('lotsize', models.IntegerField()),
                ('tax_assessment', models.IntegerField()),
                ('tax_year', models.IntegerField()),
                ('listed_by', models.CharField(max_length=255)),
            ],
        ),
    ]
