# Generated by Django 4.2.10 on 2024-03-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='lotsize',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Lot Size'),
        ),
    ]
