# Generated by Django 4.2.11 on 2024-03-08 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='type',
            field=models.CharField(choices=[('house', 'House'), ('lot', 'Lot'), ('multifamily', 'Multi-family'), ('condo', 'Condominium'), ('townhome', 'Townhome')], default='house', max_length=50),
        ),
    ]
