# Generated by Django 4.2.10 on 2024-03-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_home_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='bathrooms',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
