# Generated by Django 4.2.10 on 2024-03-05 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_home_original_url_alter_home_bathrooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='original_url',
        ),
        migrations.AddField(
            model_name='home',
            name='property_taxes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
