# Generated by Django 4.2.10 on 2024-03-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_home_original_url_home_property_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='original_url',
            field=models.URLField(max_length=255, null=True, verbose_name='Original URL'),
        ),
    ]
